environment:
  global:
    TEST_DEPENDS: "pytest numpy nibabel"

  matrix:
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

build: false

install:
  - conda create --yes -n test_env python=%PYTHON_VERSION% %TEST_DEPENDS%
  - activate test_env

test_script:
  - pytest